name: Lint with JavaScript Standard Style
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: Run standard
        run: yarn dlx standard
